# Generated by Django 3.0.2 on 2020-07-04 12:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(default='몇 번째 카드뉴스인가요?', max_length=50)),
                ('cardExplain', models.CharField(default='카드뉴스 설명을 적어주세요.', max_length=300)),
                ('cardImage', models.ImageField(blank=True, upload_to='image')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
